ui: mocha-bdd
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: oldest..latest
  - name: iphone
    version: latest
  - name: ie
    version: 10..latest